# 1. ?????? ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/jobDB?serverTimezone=Asia/Seoul&useSSL=false
spring.datasource.username=root
spring.datasource.password=7988
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA ?? (?? ? ? ??? ?? ??)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

# =================================================================
# ??? ?? API ? ?? (??? ? ? ??) ???
# =================================================================

# 1. API ?? ?? (?? ???? ??)
job.api.base-url=https://apis.data.go.kr/1051000/recruitment/list

# 2. ???? ??? ? (URL ???? ?? ??????)
job.api.service-key=7adb8c79f0b39b023435a8f94059a1e0e30d45083ef1d1bb74e69b43bbcf08d4

# 3. ?? ???? (???, ?? ?? ?? ??)
job.api.default-params=?pageNo=1&numOfRows=10&type=json